// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UpPhoneBalance.Infrastructure.Data;

#nullable disable

namespace UpPhoneBalance.Infrastructure.Migrations
{
    [DbContext(typeof(PhonePaymentsDbContext))]
    [Migration("20221030231553_PhonePaymentsPrefixes")]
    partial class PhonePaymentsPrefixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UpPhoneBalance.Domain.Entities.PhonePaymentsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UpPhoneBalance.Domain.Entities.PrefixesDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileOperatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prefixes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "701",
                            MobileOperatorName = "Activ"
                        },
                        new
                        {
                            Id = 2,
                            Key = "777",
                            MobileOperatorName = "Beeline"
                        },
                        new
                        {
                            Id = 3,
                            Key = "705",
                            MobileOperatorName = "Beeline"
                        },
                        new
                        {
                            Id = 4,
                            Key = "707",
                            MobileOperatorName = "Tele2"
                        },
                        new
                        {
                            Id = 5,
                            Key = "747",
                            MobileOperatorName = "Tele2"
                        },
                        new
                        {
                            Id = 6,
                            Key = "700",
                            MobileOperatorName = "Altel"
                        },
                        new
                        {
                            Id = 7,
                            Key = "708",
                            MobileOperatorName = "Altel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
